#define NETWORK_SECRET_SSID "A1_C5B4"
#define NETWORK_SECRET_PASS "48575443B036A4A4"

#define TOMATO_SOIL_MOISTURE_MIN 70
#define TOMATE_SOIL_MOISTURE_MAX 80

#define CUCUMBER_SOIL_MOISTURE_MIN  85
#define CUCUMBER_SOIL_MOISTURE_MAX 95
